our changes thus far

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 # bin/detect <build-dir>
 
-if [ -f $1/package.json ]; then
-  echo "Ember CLI" && exit 0
+if [ -f $1/.embedded-ember-dir ]; then
+  echo "Embedded Ember application" && exit 0
 else
-  echo "no" && exit 1
+  echo "This doesn't look like an embedded Ember application. Can't run. Please see the README for more help." && exit 1
 fi
